// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	pipeline "github.com/mehdihadeli/go-ecommerce-microservices/internal/pkg/messaging/pipeline"
	mock "github.com/stretchr/testify/mock"
)

// ConsumerPipelineConfigurationBuilderFunc is an autogenerated mock type for the ConsumerPipelineConfigurationBuilderFunc type
type ConsumerPipelineConfigurationBuilderFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ConsumerPipelineConfigurationBuilderFunc) Execute(_a0 pipeline.ConsumerPipelineConfigurationBuilder) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewConsumerPipelineConfigurationBuilderFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewConsumerPipelineConfigurationBuilderFunc creates a new instance of ConsumerPipelineConfigurationBuilderFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConsumerPipelineConfigurationBuilderFunc(t mockConstructorTestingTNewConsumerPipelineConfigurationBuilderFunc) *ConsumerPipelineConfigurationBuilderFunc {
	mock := &ConsumerPipelineConfigurationBuilderFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
