// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	reflect "reflect"

	mock "github.com/stretchr/testify/mock"

	types "github.com/mehdihadeli/go-food-delivery-microservices/internal/pkg/core/messaging/types"
	serializer "github.com/mehdihadeli/go-food-delivery-microservices/internal/pkg/core/serializer"
)

// MessageSerializer is an autogenerated mock type for the MessageSerializer type
type MessageSerializer struct {
	mock.Mock
}

type MessageSerializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageSerializer) EXPECT() *MessageSerializer_Expecter {
	return &MessageSerializer_Expecter{mock: &_m.Mock}
}

// ContentType provides a mock function with given fields:
func (_m *MessageSerializer) ContentType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContentType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MessageSerializer_ContentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContentType'
type MessageSerializer_ContentType_Call struct {
	*mock.Call
}

// ContentType is a helper method to define mock.On call
func (_e *MessageSerializer_Expecter) ContentType() *MessageSerializer_ContentType_Call {
	return &MessageSerializer_ContentType_Call{Call: _e.mock.On("ContentType")}
}

func (_c *MessageSerializer_ContentType_Call) Run(run func()) *MessageSerializer_ContentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MessageSerializer_ContentType_Call) Return(_a0 string) *MessageSerializer_ContentType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageSerializer_ContentType_Call) RunAndReturn(run func() string) *MessageSerializer_ContentType_Call {
	_c.Call.Return(run)
	return _c
}

// Deserialize provides a mock function with given fields: data, messageType, contentType
func (_m *MessageSerializer) Deserialize(data []byte, messageType string, contentType string) (types.IMessage, error) {
	ret := _m.Called(data, messageType, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Deserialize")
	}

	var r0 types.IMessage
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, string, string) (types.IMessage, error)); ok {
		return rf(data, messageType, contentType)
	}
	if rf, ok := ret.Get(0).(func([]byte, string, string) types.IMessage); ok {
		r0 = rf(data, messageType, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.IMessage)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, string, string) error); ok {
		r1 = rf(data, messageType, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageSerializer_Deserialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deserialize'
type MessageSerializer_Deserialize_Call struct {
	*mock.Call
}

// Deserialize is a helper method to define mock.On call
//   - data []byte
//   - messageType string
//   - contentType string
func (_e *MessageSerializer_Expecter) Deserialize(data interface{}, messageType interface{}, contentType interface{}) *MessageSerializer_Deserialize_Call {
	return &MessageSerializer_Deserialize_Call{Call: _e.mock.On("Deserialize", data, messageType, contentType)}
}

func (_c *MessageSerializer_Deserialize_Call) Run(run func(data []byte, messageType string, contentType string)) *MessageSerializer_Deserialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MessageSerializer_Deserialize_Call) Return(_a0 types.IMessage, _a1 error) *MessageSerializer_Deserialize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageSerializer_Deserialize_Call) RunAndReturn(run func([]byte, string, string) (types.IMessage, error)) *MessageSerializer_Deserialize_Call {
	_c.Call.Return(run)
	return _c
}

// DeserializeObject provides a mock function with given fields: data, messageType, contentType
func (_m *MessageSerializer) DeserializeObject(data []byte, messageType string, contentType string) (interface{}, error) {
	ret := _m.Called(data, messageType, contentType)

	if len(ret) == 0 {
		panic("no return value specified for DeserializeObject")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, string, string) (interface{}, error)); ok {
		return rf(data, messageType, contentType)
	}
	if rf, ok := ret.Get(0).(func([]byte, string, string) interface{}); ok {
		r0 = rf(data, messageType, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, string, string) error); ok {
		r1 = rf(data, messageType, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageSerializer_DeserializeObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeserializeObject'
type MessageSerializer_DeserializeObject_Call struct {
	*mock.Call
}

// DeserializeObject is a helper method to define mock.On call
//   - data []byte
//   - messageType string
//   - contentType string
func (_e *MessageSerializer_Expecter) DeserializeObject(data interface{}, messageType interface{}, contentType interface{}) *MessageSerializer_DeserializeObject_Call {
	return &MessageSerializer_DeserializeObject_Call{Call: _e.mock.On("DeserializeObject", data, messageType, contentType)}
}

func (_c *MessageSerializer_DeserializeObject_Call) Run(run func(data []byte, messageType string, contentType string)) *MessageSerializer_DeserializeObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MessageSerializer_DeserializeObject_Call) Return(_a0 interface{}, _a1 error) *MessageSerializer_DeserializeObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageSerializer_DeserializeObject_Call) RunAndReturn(run func([]byte, string, string) (interface{}, error)) *MessageSerializer_DeserializeObject_Call {
	_c.Call.Return(run)
	return _c
}

// DeserializeType provides a mock function with given fields: data, messageType, contentType
func (_m *MessageSerializer) DeserializeType(data []byte, messageType reflect.Type, contentType string) (types.IMessage, error) {
	ret := _m.Called(data, messageType, contentType)

	if len(ret) == 0 {
		panic("no return value specified for DeserializeType")
	}

	var r0 types.IMessage
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, reflect.Type, string) (types.IMessage, error)); ok {
		return rf(data, messageType, contentType)
	}
	if rf, ok := ret.Get(0).(func([]byte, reflect.Type, string) types.IMessage); ok {
		r0 = rf(data, messageType, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.IMessage)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, reflect.Type, string) error); ok {
		r1 = rf(data, messageType, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageSerializer_DeserializeType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeserializeType'
type MessageSerializer_DeserializeType_Call struct {
	*mock.Call
}

// DeserializeType is a helper method to define mock.On call
//   - data []byte
//   - messageType reflect.Type
//   - contentType string
func (_e *MessageSerializer_Expecter) DeserializeType(data interface{}, messageType interface{}, contentType interface{}) *MessageSerializer_DeserializeType_Call {
	return &MessageSerializer_DeserializeType_Call{Call: _e.mock.On("DeserializeType", data, messageType, contentType)}
}

func (_c *MessageSerializer_DeserializeType_Call) Run(run func(data []byte, messageType reflect.Type, contentType string)) *MessageSerializer_DeserializeType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(reflect.Type), args[2].(string))
	})
	return _c
}

func (_c *MessageSerializer_DeserializeType_Call) Return(_a0 types.IMessage, _a1 error) *MessageSerializer_DeserializeType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageSerializer_DeserializeType_Call) RunAndReturn(run func([]byte, reflect.Type, string) (types.IMessage, error)) *MessageSerializer_DeserializeType_Call {
	_c.Call.Return(run)
	return _c
}

// Serialize provides a mock function with given fields: message
func (_m *MessageSerializer) Serialize(message types.IMessage) (*serializer.EventSerializationResult, error) {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 *serializer.EventSerializationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(types.IMessage) (*serializer.EventSerializationResult, error)); ok {
		return rf(message)
	}
	if rf, ok := ret.Get(0).(func(types.IMessage) *serializer.EventSerializationResult); ok {
		r0 = rf(message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serializer.EventSerializationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(types.IMessage) error); ok {
		r1 = rf(message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageSerializer_Serialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serialize'
type MessageSerializer_Serialize_Call struct {
	*mock.Call
}

// Serialize is a helper method to define mock.On call
//   - message types.IMessage
func (_e *MessageSerializer_Expecter) Serialize(message interface{}) *MessageSerializer_Serialize_Call {
	return &MessageSerializer_Serialize_Call{Call: _e.mock.On("Serialize", message)}
}

func (_c *MessageSerializer_Serialize_Call) Run(run func(message types.IMessage)) *MessageSerializer_Serialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.IMessage))
	})
	return _c
}

func (_c *MessageSerializer_Serialize_Call) Return(_a0 *serializer.EventSerializationResult, _a1 error) *MessageSerializer_Serialize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageSerializer_Serialize_Call) RunAndReturn(run func(types.IMessage) (*serializer.EventSerializationResult, error)) *MessageSerializer_Serialize_Call {
	_c.Call.Return(run)
	return _c
}

// SerializeEnvelop provides a mock function with given fields: messageEnvelop
func (_m *MessageSerializer) SerializeEnvelop(messageEnvelop types.MessageEnvelope) (*serializer.EventSerializationResult, error) {
	ret := _m.Called(messageEnvelop)

	if len(ret) == 0 {
		panic("no return value specified for SerializeEnvelop")
	}

	var r0 *serializer.EventSerializationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(types.MessageEnvelope) (*serializer.EventSerializationResult, error)); ok {
		return rf(messageEnvelop)
	}
	if rf, ok := ret.Get(0).(func(types.MessageEnvelope) *serializer.EventSerializationResult); ok {
		r0 = rf(messageEnvelop)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serializer.EventSerializationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(types.MessageEnvelope) error); ok {
		r1 = rf(messageEnvelop)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageSerializer_SerializeEnvelop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SerializeEnvelop'
type MessageSerializer_SerializeEnvelop_Call struct {
	*mock.Call
}

// SerializeEnvelop is a helper method to define mock.On call
//   - messageEnvelop types.MessageEnvelope
func (_e *MessageSerializer_Expecter) SerializeEnvelop(messageEnvelop interface{}) *MessageSerializer_SerializeEnvelop_Call {
	return &MessageSerializer_SerializeEnvelop_Call{Call: _e.mock.On("SerializeEnvelop", messageEnvelop)}
}

func (_c *MessageSerializer_SerializeEnvelop_Call) Run(run func(messageEnvelop types.MessageEnvelope)) *MessageSerializer_SerializeEnvelop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.MessageEnvelope))
	})
	return _c
}

func (_c *MessageSerializer_SerializeEnvelop_Call) Return(_a0 *serializer.EventSerializationResult, _a1 error) *MessageSerializer_SerializeEnvelop_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageSerializer_SerializeEnvelop_Call) RunAndReturn(run func(types.MessageEnvelope) (*serializer.EventSerializationResult, error)) *MessageSerializer_SerializeEnvelop_Call {
	_c.Call.Return(run)
	return _c
}

// SerializeObject provides a mock function with given fields: message
func (_m *MessageSerializer) SerializeObject(message interface{}) (*serializer.EventSerializationResult, error) {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for SerializeObject")
	}

	var r0 *serializer.EventSerializationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (*serializer.EventSerializationResult, error)); ok {
		return rf(message)
	}
	if rf, ok := ret.Get(0).(func(interface{}) *serializer.EventSerializationResult); ok {
		r0 = rf(message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serializer.EventSerializationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageSerializer_SerializeObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SerializeObject'
type MessageSerializer_SerializeObject_Call struct {
	*mock.Call
}

// SerializeObject is a helper method to define mock.On call
//   - message interface{}
func (_e *MessageSerializer_Expecter) SerializeObject(message interface{}) *MessageSerializer_SerializeObject_Call {
	return &MessageSerializer_SerializeObject_Call{Call: _e.mock.On("SerializeObject", message)}
}

func (_c *MessageSerializer_SerializeObject_Call) Run(run func(message interface{})) *MessageSerializer_SerializeObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MessageSerializer_SerializeObject_Call) Return(_a0 *serializer.EventSerializationResult, _a1 error) *MessageSerializer_SerializeObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageSerializer_SerializeObject_Call) RunAndReturn(run func(interface{}) (*serializer.EventSerializationResult, error)) *MessageSerializer_SerializeObject_Call {
	_c.Call.Return(run)
	return _c
}

// Serializer provides a mock function with given fields:
func (_m *MessageSerializer) Serializer() serializer.Serializer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Serializer")
	}

	var r0 serializer.Serializer
	if rf, ok := ret.Get(0).(func() serializer.Serializer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(serializer.Serializer)
		}
	}

	return r0
}

// MessageSerializer_Serializer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serializer'
type MessageSerializer_Serializer_Call struct {
	*mock.Call
}

// Serializer is a helper method to define mock.On call
func (_e *MessageSerializer_Expecter) Serializer() *MessageSerializer_Serializer_Call {
	return &MessageSerializer_Serializer_Call{Call: _e.mock.On("Serializer")}
}

func (_c *MessageSerializer_Serializer_Call) Run(run func()) *MessageSerializer_Serializer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MessageSerializer_Serializer_Call) Return(_a0 serializer.Serializer) *MessageSerializer_Serializer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageSerializer_Serializer_Call) RunAndReturn(run func() serializer.Serializer) *MessageSerializer_Serializer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageSerializer creates a new instance of MessageSerializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageSerializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageSerializer {
	mock := &MessageSerializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
