// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ProductsModuleConfigurator is an autogenerated mock type for the ProductsModuleConfigurator type
type ProductsModuleConfigurator struct {
	mock.Mock
}

// ConfigureProductsModule provides a mock function with given fields: ctx
func (_m *ProductsModuleConfigurator) ConfigureProductsModule(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewProductsModuleConfigurator interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductsModuleConfigurator creates a new instance of ProductsModuleConfigurator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductsModuleConfigurator(t mockConstructorTestingTNewProductsModuleConfigurator) *ProductsModuleConfigurator {
	mock := &ProductsModuleConfigurator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
