// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import (
	data "github.com/mehdihadeli/go-ecommerce-microservices/internal/services/catalogwriteservice/internal/products/contracts/data"
	mock "github.com/stretchr/testify/mock"
)

// CatalogContext is an autogenerated mock type for the CatalogContext type
type CatalogContext struct {
	mock.Mock
}

type CatalogContext_Expecter struct {
	mock *mock.Mock
}

func (_m *CatalogContext) EXPECT() *CatalogContext_Expecter {
	return &CatalogContext_Expecter{mock: &_m.Mock}
}

// Products provides a mock function with given fields:
func (_m *CatalogContext) Products() data.ProductRepository {
	ret := _m.Called()

	var r0 data.ProductRepository
	if rf, ok := ret.Get(0).(func() data.ProductRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(data.ProductRepository)
		}
	}

	return r0
}

// CatalogContext_Products_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Products'
type CatalogContext_Products_Call struct {
	*mock.Call
}

// Products is a helper method to define mock.On call
func (_e *CatalogContext_Expecter) Products() *CatalogContext_Products_Call {
	return &CatalogContext_Products_Call{Call: _e.mock.On("Products")}
}

func (_c *CatalogContext_Products_Call) Run(run func()) *CatalogContext_Products_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CatalogContext_Products_Call) Return(_a0 data.ProductRepository) *CatalogContext_Products_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CatalogContext_Products_Call) RunAndReturn(run func() data.ProductRepository) *CatalogContext_Products_Call {
	_c.Call.Return(run)
	return _c
}

// NewCatalogContext creates a new instance of CatalogContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCatalogContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *CatalogContext {
	mock := &CatalogContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
