package app

const (
	DefaultSourceName = "app"
	Consumer          = "app.consumer"
	EventHandler      = "app.event-handler"
	Subscription      = "app.subscription"
	Stream            = "app.stream"
	Partition         = "app.partition"
	Request           = "app.request"
	RequestName       = "app.request_name"
	RequestResultName = "app.request_result_name"
	RequestResult     = "app.request_result"
	Command           = "app.command"
	CommandName       = "app.command_name"
	CommandResult     = "app.command_result"
	CommandResultName = "app.command_result_name"
	Query             = "app.query"
	QueryName         = "app.query_name"
	QueryResult       = "app.query_result"
	QueryResultName   = "app.query_result_name"
	Event             = "app.event"
	EventName         = "app.event_name"
	EventResult       = "app.event_result"
	EventResultName   = "app.event_result_name"
)
