# https://containers.dev/guide/dockerfile#dockerfile
# https://github.com/devcontainers/templates/tree/main/src/go
# https://github.com/devcontainers/images/tree/main/src/go

FROM mcr.microsoft.com/devcontainers/go:1.22-bookworm

# Add additional commands
