// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	metadata "github.com/mehdihadeli/store-golang-microservice-sample/pkg/core/metadata"
	mock "github.com/stretchr/testify/mock"
)

// MetadataSerializer is an autogenerated mock type for the MetadataSerializer type
type MetadataSerializer struct {
	mock.Mock
}

// Deserialize provides a mock function with given fields: bytes
func (_m *MetadataSerializer) Deserialize(bytes []byte) (metadata.Metadata, error) {
	ret := _m.Called(bytes)

	var r0 metadata.Metadata
	if rf, ok := ret.Get(0).(func([]byte) metadata.Metadata); ok {
		r0 = rf(bytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.Metadata)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(bytes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Serialize provides a mock function with given fields: meta
func (_m *MetadataSerializer) Serialize(meta metadata.Metadata) ([]byte, error) {
	ret := _m.Called(meta)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(metadata.Metadata) []byte); ok {
		r0 = rf(meta)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(metadata.Metadata) error); ok {
		r1 = rf(meta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMetadataSerializer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMetadataSerializer creates a new instance of MetadataSerializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMetadataSerializer(t mockConstructorTestingTNewMetadataSerializer) *MetadataSerializer {
	mock := &MetadataSerializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
