// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import (
	domain "github.com/mehdihadeli/go-ecommerce-microservices/internal/pkg/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// Apply is an autogenerated mock type for the Apply type
type Apply struct {
	mock.Mock
}

type Apply_Expecter struct {
	mock *mock.Mock
}

func (_m *Apply) EXPECT() *Apply_Expecter {
	return &Apply_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: event, isNew
func (_m *Apply) Apply(event domain.IDomainEvent, isNew bool) error {
	ret := _m.Called(event, isNew)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.IDomainEvent, bool) error); ok {
		r0 = rf(event, isNew)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Apply_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type Apply_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - event domain.IDomainEvent
//   - isNew bool
func (_e *Apply_Expecter) Apply(event interface{}, isNew interface{}) *Apply_Apply_Call {
	return &Apply_Apply_Call{Call: _e.mock.On("Apply", event, isNew)}
}

func (_c *Apply_Apply_Call) Run(run func(event domain.IDomainEvent, isNew bool)) *Apply_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.IDomainEvent), args[1].(bool))
	})
	return _c
}

func (_c *Apply_Apply_Call) Return(_a0 error) *Apply_Apply_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Apply_Apply_Call) RunAndReturn(run func(domain.IDomainEvent, bool) error) *Apply_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// NewApply creates a new instance of Apply. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApply(t interface {
	mock.TestingT
	Cleanup(func())
}) *Apply {
	mock := &Apply{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
