// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/mehdihadeli/go-ecommerce-microservices/internal/pkg/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// WhenFunc is an autogenerated mock type for the WhenFunc type
type WhenFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: event
func (_m *WhenFunc) Execute(event domain.IDomainEvent) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.IDomainEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewWhenFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewWhenFunc creates a new instance of WhenFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWhenFunc(t mockConstructorTestingTNewWhenFunc) *WhenFunc {
	mock := &WhenFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
