definitions:
  github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_dtos_v1.OrderReadDto:
    properties:
      accountEmail:
        type: string
      cancelReason:
        type: string
      canceled:
        type: boolean
      completed:
        type: boolean
      createdAt:
        type: string
      deliveredTime:
        type: string
      deliveryAddress:
        type: string
      id:
        type: string
      orderId:
        type: string
      paid:
        type: boolean
      paymentId:
        type: string
      shopItems:
        items:
          $ref: '#/definitions/github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_dtos_v1.ShopItemReadDto'
        type: array
      submitted:
        type: boolean
      totalPrice:
        type: number
      updatedAt:
        type: string
    type: object
  github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_dtos_v1.ShopItemDto:
    properties:
      description:
        type: string
      price:
        type: number
      quantity:
        type: integer
      title:
        type: string
    type: object
  github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_dtos_v1.ShopItemReadDto:
    properties:
      description:
        type: string
      price:
        type: number
      quantity:
        type: integer
      title:
        type: string
    type: object
  ? github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_features_creating_order_v1_dtos.CreateOrderRequestDto
  : properties:
      accountEmail:
        type: string
      deliveryAddress:
        type: string
      deliveryTime:
        type: string
      shopItems:
        items:
          $ref: '#/definitions/github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_dtos_v1.ShopItemDto'
        type: array
    type: object
  ? github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_features_creating_order_v1_dtos.CreateOrderResponseDto
  : properties:
      Id:
        type: string
    type: object
  ? github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_features_getting_order_by_id_v1_dtos.GetOrderByIdResponseDto
  : properties:
      order:
        $ref: '#/definitions/github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_dtos_v1.OrderReadDto'
    type: object
  ? github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_features_getting_orders_v1_dtos.GetOrdersResponseDto
  : properties:
      orders:
        $ref: '#/definitions/utils.ListResult-github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_dtos_v1_OrderReadDto'
    type: object
  utils.FilterModel:
    properties:
      comparison:
        type: string
      field:
        type: string
      value:
        type: string
    type: object
  ? utils.ListResult-github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_dtos_v1_OrderReadDto
  : properties:
      items:
        items:
          $ref: '#/definitions/github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_dtos_v1.OrderReadDto'
        type: array
      page:
        type: integer
      size:
        type: integer
      totalItems:
        type: integer
      totalPage:
        type: integer
    type: object
info:
  contact:
    name: Mehdi Hadeli
    url: https://github.com/mehdihadeli
  description: Orders Service Api
  title: Orders Service Api
  version: "1.0"
paths:
  /api/v1/orders:
    get:
      consumes:
      - application/json
      description: Get all orders
      parameters:
      - in: query
        name: orderBy
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_features_getting_orders_v1_dtos.GetOrdersResponseDto'
      summary: Get all orders
      tags:
      - Orders
    post:
      consumes:
      - application/json
      description: Create new order
      parameters:
      - description: Order data
        in: body
        name: CreateOrderRequestDto
        required: true
        schema:
          $ref: '#/definitions/github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_features_creating_order_v1_dtos.CreateOrderRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_features_creating_order_v1_dtos.CreateOrderResponseDto'
      summary: Create order
      tags:
      - Orders
  /api/v1/orders/{id}:
    get:
      consumes:
      - application/json
      description: Get order by id
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_mehdihadeli_go-food-delivery-microservices_internal_services_orderservice_internal_orders_features_getting_order_by_id_v1_dtos.GetOrderByIdResponseDto'
      summary: Get order by id
      tags:
      - Orders
swagger: "2.0"
